### ISSUE TITLE
Ability to control individual Publications through the API?

### ISSUE THREAD

**Issue by domenicdistefano** [datarhei/core#19]
Is it possible to stop / start individual Publications? Reading the API docs I only can see a way to stop / start RTMP but what if I have multiple cameras going going to YouTube for instance and I only want to stop / start one of them?

**Comment by ioppermann** [comment]
The UI creates processes that have a name with a certain pattern. The pattern is `restreamer-ui:egress:[name of the publication]:[UUIDv4]`.

Via the API you can list all processes. There you should see processes with matching name if you have added some publication services. Then you can simply send a `start` or `stop` command to that process.

**Comment by domenicdistefano** [comment]
Thank you! I will give it a try.
