### ISSUE TITLE
Is there any way to change the environment variable once start/run( at running mode, wihtout stope or retart) the project?

### ISSUE THREAD

**Issue by NikunjGadhiya07** [datarhei/core#7]
Hi, there

I need to change the value of "CORE_API_AUTH_AUTH0_TENANTS" environment variable. (At a running time without stopping or restarting the project).

eg, 
I'm using auth0,
I want to add a new user or change the domain name.
I need to change the "Tenants" value.

because I have seen I think, env value is set only once at the start of the project.
is this right?

thanks,

**Comment by ioppermann** [comment]
It is currently not possible to change the tenants or to add/remove users without restarting. A user management via API is on our roadmap.
