### ISSUE TITLE
Preview image does not update

### ISSUE THREAD

**Issue by woiczi** [datarhei/core#9]
the preview image is not updating according to the setup. The update intervall is set to 10 sec, but the real update is (randomly) after around 30 min.
I couldn´t find a entry about the update time in the config.js files, only the link.
how to set the update of the images to e.g. 10sec

testet on Release: restreamer-v2.5.0 and restreamer-v2.4.2

**Comment by jstabenow** [comment]
In this case, the HLS stream is faulty or the system overloaded. 
Please attach the [process report](https://docs.datarhei.com/restreamer/knowledge-base/manual/process-report) of the channel.

Note:
Snapshots will only be taken if the channel has a connection.
